CREATE TABLE USER_ROLE (
	UR_ID	INT	PRIMARY KEY,
	UR_NAME	VARCHAR2(50)
);

CREATE TABLE OVERALL_STATUS (
    OS_ID INT PRIMARY KEY,
    OS_NAME VARCHAR2(4)
);

CREATE TABLE TRAINING_TYPE(
	TT_ID	INT	PRIMARY KEY,
	TT_DESC VARCHAR2(50)
);

CREATE TABLE VERTICAL_TYPE(
	VER_ID 	INT	PRIMARY KEY,
	VER_NAME 	VARCHAR2(50),
	VER_HEAD	VARCHAR2(50)
);

CREATE TABLE VENDOR(
	VEN_ID	INT	PRIMARY KEY,
	VEN_NAME 	VARCHAR2(50),
	VEN_LOCATION 	VARCHAR2(50),
	VEN_ADDRESS	VARCHAR2(100),
	VEN_SPOC	VARCHAR2(50) NOT NULL,
	VEN_PHONE	VARCHAR2(15) NOT NULL,
	VEN_EMAIL	VARCHAR2(50) NOT NULL
);

CREATE TABLE TRAINING_REQUEST_FORM(
	TRF_ID	INT	PRIMARY KEY,
	VER_ID	INT,
	VEN_ID 	INT,
	TT_ID 	INT,
	TRF_PROJECT_ID	VARCHAR2(50),
	TRF_TECHNOLOGY	VARCHAR2(100),
	TRF_TRAINING_OBJECTIVES 	VARCHAR2(1000),
	TRF_DATE_REQUESTED 	DATE,
	TRF_PROPOSED_END_DATE DATE,
	TRF_PROJECT_TRAINING_SPOC 	VARCHAR2(50),
	TRF_APPROX_NO_EMPLOYEES	INT,
	TRF_REQUESTOR_EMPLOYEE_ID VARCHAR2(50),
	TRF_APPROVED_FILE_LOCATION VARCHAR2(100),
	TRF_TRAINING_SOURCE INT,
    TRF_HIDE_STATUS INT,

	CONSTRAINT fk_trf_ver_id
		FOREIGN KEY (VER_ID)
		REFERENCES VERTICAL_TYPE(VER_ID) ON DELETE CASCADE,
	CONSTRAINT fk_trf_ven_id
		FOREIGN KEY (VEN_ID)
		REFERENCES VENDOR(VEN_ID) ON DELETE CASCADE,
	CONSTRAINT fk_trf_tt_id
		FOREIGN KEY (TT_ID)
		REFERENCES TRAINING_TYPE(TT_ID) ON DELETE CASCADE
);

CREATE TABLE LD_TEAM(
	LD_USER_EMAIL VARCHAR2(50) PRIMARY KEY,
	LD_VER_REP	INT,
	UR_ID	INT,
	LD_USER_NAME VARCHAR2(50),
	LD_USER_PHONE VARCHAR2(15),
	LD_USER_PASSWORD VARCHAR2(30),
	CONSTRAINT fk_ld_ver_rep
		FOREIGN KEY (LD_VER_REP)
		REFERENCES VERTICAL_TYPE(VER_ID) ON DELETE CASCADE,
	CONSTRAINT fk_ld_ur_id
		FOREIGN KEY (UR_ID)
		REFERENCES USER_ROLE(UR_ID) ON DELETE CASCADE
);

CREATE TABLE DEVELOPER_TRAINING_MEMBER(
	DTM_ID	INT PRIMARY KEY,
	VER_ID 	INT,
	DTM_NAME VARCHAR2(50),
	DTM_PHONE VARCHAR2(15),
	DTM_EMAIL VARCHAR2(50),
	DTM_EMPLOYEE_ID VARCHAR2(50),
    DTM_TECH_SPECIALTY VARCHAR2(1000),
	CONSTRAINT fk_dtm_ver_id
		FOREIGN KEY (VER_ID)
		REFERENCES VERTICAL_TYPE(VER_ID) ON DELETE CASCADE
);

CREATE TABLE LD_TRAINING_MEMBER(
	LDTM_ID INT PRIMARY KEY,
	LDTM_NAME VARCHAR2(50),
	LDTM_LOCATION VARCHAR2(200),
	LDTM_EMAIL VARCHAR2(50),
	LDTM_PHONE VARCHAR2(15),
	LDTM_TECH_SPECIALTY VARCHAR2(1000)
);

CREATE TABLE IN_PROGRESS_TRAINING(
	IPT_ID	INT	PRIMARY KEY,
	VER_ID	INT,
	VEN_ID 	INT,
	TT_ID 	INT,
    TRF_ID	INT,
    OS_ID INT,
	IPT_PROJECT_ID	VARCHAR2(50),
	IPT_TECHNOLOGY	VARCHAR2(100),
	IPT_TRAINING_OBJECTIVES 	VARCHAR2(1000),
	IPT_DATE_REQUESTED 	DATE,
    IPT_PROPOSED_START_DATE DATE,
	IPT_PROPOSED_END_DATE DATE,
	IPT_PROJECT_TRAINING_SPOC 	VARCHAR2(50),
	IPT_APPROX_NO_EMPLOYEES	INT,
	IPT_REQUESTOR_EMPLOYEE_ID VARCHAR2(50),
	IPT_APPROVED_FILE_LOCATION VARCHAR2(100),
	IPT_TRAINING_SOURCE INT,
    IPT_PROPOSED_LOCATION  VARCHAR2(50),
    IPT_PROPOSED_START_TIME VARCHAR2(4),
    IPT_PROPOSED_END_TIME VARCHAR2(4),
    
	CONSTRAINT fk_ipt_ver_id
		FOREIGN KEY (VER_ID)
		REFERENCES VERTICAL_TYPE(VER_ID) ON DELETE CASCADE,
	CONSTRAINT fk_ipt_ven_id
		FOREIGN KEY (VEN_ID)
		REFERENCES VENDOR(VEN_ID) ON DELETE CASCADE,
	CONSTRAINT fk_ipt_tt_id
		FOREIGN KEY (TT_ID)
		REFERENCES TRAINING_TYPE(TT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_ipt_trf_id
        FOREIGN KEY(TRF_ID)
        REFERENCES TRAINING_REQUEST_FORM ON DELETE CASCADE,
    CONSTRAINT fk_ipt_os_id 
        FOREIGN KEY (OS_ID)
        REFERENCES OVERALL_STATUS ON DELETE CASCADE
);

CREATE TABLE CONFIRMED_TRAINING(
	CT_ID	INT	PRIMARY KEY,
	VER_ID	INT,
	VEN_ID 	INT,
	TT_ID 	INT,
    TRF_ID	INT,
    OS_ID INT,
    IPT_ID INT,
	CT_PROJECT_ID	VARCHAR2(50),
	CT_TECHNOLOGY	VARCHAR2(100),
	CT_TRAINING_OBJECTIVES 	VARCHAR2(1000),
	CT_DATE_REQUESTED 	DATE,
    CT_PROPOSED_START_DATE DATE,
	CT_PROPOSED_END_DATE DATE,
	CT_PROJECT_TRAINING_SPOC 	VARCHAR2(50),
	CT_APPROX_NO_EMPLOYEES	INT,
	CT_REQUESTOR_EMPLOYEE_ID VARCHAR2(50),
	CT_APPROVED_FILE_LOCATION VARCHAR2(100),
	CT_TRAINING_SOURCE INT,
    CT_HIDE_STATUS INT,
    CT_PROPOSED_LOCATION  VARCHAR2(50),
    CT_PROPOSED_START_TIME VARCHAR2(4),
    CT_PROPOSED_END_TIME VARCHAR2(4),
    
	CONSTRAINT fk_ct_ver_id
		FOREIGN KEY (VER_ID)
		REFERENCES VERTICAL_TYPE(VER_ID) ON DELETE CASCADE,
	CONSTRAINT fk_ct_ven_id
		FOREIGN KEY (VEN_ID)
		REFERENCES VENDOR(VEN_ID) ON DELETE CASCADE,
	CONSTRAINT fk_ct_tt_id
		FOREIGN KEY (TT_ID)
		REFERENCES TRAINING_TYPE(TT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_ct_trf_id
        FOREIGN KEY(TRF_ID)
        REFERENCES TRAINING_REQUEST_FORM ON DELETE CASCADE,
    CONSTRAINT fk_ct_os_id 
        FOREIGN KEY (OS_ID)
        REFERENCES OVERALL_STATUS ON DELETE CASCADE,
    CONSTRAINT fk_ct_ipt_id
        FOREIGN KEY(IPT_ID)
        REFERENCES IN_PROGRESS_TRAINING ON DELETE CASCADE
);

CREATE TABLE INTERNAL_TRAINING(
	IT_ID INT PRIMARY KEY,
	IPT_ID INT,
	LDTM_ID INT,
	CONSTRAINT fk_it_ipt_id
		FOREIGN KEY (IPT_ID)
		REFERENCES IN_PROGRESS_TRAINING(IPT_ID) ON DELETE CASCADE,
	CONSTRAINT fk_it_ldtm_id
		FOREIGN KEY (LDTM_ID)
		REFERENCES LD_TRAINING_MEMBER(LDTM_ID) ON DELETE CASCADE
);

CREATE TABLE DEV_TRAINING(
	DT_ID INT PRIMARY KEY,
	IPT_ID INT,
	DTM_ID INT,
	CONSTRAINT fk_dt_ipt_id
		FOREIGN KEY (IPT_ID)
		REFERENCES IN_PROGRESS_TRAINING(IPT_ID) ON DELETE CASCADE,
	CONSTRAINT fk_dt_dtm_id
		FOREIGN KEY (DTM_ID)
		REFERENCES DEVELOPER_TRAINING_MEMBER(DTM_ID) ON DELETE CASCADE
);

CREATE TABLE VENDOR_TRAINING(
	VT_ID INT PRIMARY KEY,
	IPT_ID INT,
	VEN_ID INT,
	CONSTRAINT fk_vt_ipt_id
		FOREIGN KEY (IPT_ID)
		REFERENCES IN_PROGRESS_TRAINING(IPT_ID) ON DELETE CASCADE,
	CONSTRAINT fk_vt_ven_id
		FOREIGN KEY (VEN_ID)
		REFERENCES VENDOR(VEN_ID) ON DELETE CASCADE
);











