CREATE TABLE TRAINING_STATUS ( 
    TSTATUS_ID 	INT	PRIMARY KEY, 
    TSTATUS_DESC VARCHAR2(50) NOT NULL
);

CREATE TABLE USER_ROLE (
	UR_ID	INT	PRIMARY KEY,
	UR_NAME	VARCHAR2(50)
);

CREATE TABLE TRAINING_TYPE(
	TT_ID	INT	PRIMARY KEY,
	TT_DESC VARCHAR2(50)
);

CREATE TABLE VERTICAL_TYPE(
	VER_ID 	INT	PRIMARY KEY,
	VER_NAME 	VARCHAR2(50),
	VER_HEAD	VARCHAR2(50)
);

CREATE TABLE VENDOR(
	VEN_ID	INT	PRIMARY KEY,
	VEN_NAME 	VARCHAR2(50),
	VEN_LOCATION 	VARCHAR2(50),
	VEN_ADDRESS	VARCHAR2(100),
	VEN_SPOC	VARCHAR2(50) NOT NULL,
	VEN_PHONE	VARCHAR2(15) NOT NULL,
	VEN_EMAIL	VARCHAR2(50) NOT NULL
);

CREATE TABLE TRAINING_REQUEST_FORM(
	TRF_ID	INT	PRIMARY KEY,
	VER_ID	INT,
	VEN_ID 	INT,
	TT_ID 	INT,
	TRF_PROJECT_ID	VARCHAR2(50),
	TRF_TECHNOLOGY	VARCHAR2(100),
	TRF_TRAINING_OBJECTIVES 	VARCHAR2(1000),
	TRF_DATE_REQUESTED 	DATE,
	TRF_PROPOSED_END_DATE DATE,
	TRF_PROJECT_TRAINING_SPOC 	VARCHAR2(50),
	TRF_APPROX_NO_EMPLOYEES	INT,
	TRF_REQUESTOR_EMPLOYEE_ID VARCHAR2(50),
	TRF_APPROVED_FILE_LOCATION VARCHAR2(100),
	TRF_TRAINING_SOURCE INT,

	CONSTRAINT fk_trf_ver_id
		FOREIGN KEY (VER_ID)
		REFERENCES VERTICAL_TYPE(VER_ID),
	CONSTRAINT fk_trf_ven_id
		FOREIGN KEY (VEN_ID)
		REFERENCES VENDOR(VEN_ID),
	CONSTRAINT fk_trf_tt_id
		FOREIGN KEY (TT_ID)
		REFERENCES TRAINING_TYPE(TT_ID)
);

CREATE TABLE LD_TEAM(
	LD_USER_EMAIL VARCHAR2(50) PRIMARY KEY,
	LD_VER_REP	INT,
	UR_ID	INT,
	LD_USER_NAME VARCHAR2(50),
	LD_USER_PHONE VARCHAR2(15),
	LD_USER_PASSWORD VARCHAR2(30),
	CONSTRAINT fk_ld_ver_rep
		FOREIGN KEY (LD_VER_REP)
		REFERENCES VERTICAL_TYPE(VER_ID),
	CONSTRAINT fk_ld_ur_id
		FOREIGN KEY (UR_ID)
		REFERENCES USER_ROLE(UR_ID)
);

CREATE TABLE DEVELOPER_TRAINING_MEMBER(
	DTM_ID	INT PRIMARY KEY,
	VER_ID 	INT,
	DTM_NAME VARCHAR2(50),
	DTM_PHONE VARCHAR2(15),
	DTM_EMAIL VARCHAR2(50),
	DTM_EMPLOYEE_ID VARCHAR2(50),
    DTM_TECH_SPECIALTY VARCHAR2(1000),
	CONSTRAINT fk_dtm_ver_id
		FOREIGN KEY (VER_ID)
		REFERENCES VERTICAL_TYPE(VER_ID)
);

CREATE TABLE LD_TRAINING_MEMBER(
	LDTM_ID INT PRIMARY KEY,
	LDTM_NAME VARCHAR2(50),
	LDTM_LOCATION VARCHAR2(200),
	LDTM_EMAIL VARCHAR2(50),
	LDTM_PHONE VARCHAR2(15),
	LDTM_TECH_SPECIALTY VARCHAR2(1000)
);

CREATE TABLE IN_PROGRESS_TRAINING(
	IPT_ID INT PRIMARY KEY,
	TSTATUS_ID INT,
	TT_ID INT,
	LD_USER_EMAIL VARCHAR2(50),
    VER_ID INT,
	TRF_ID INT,
	IPT_START_DATE DATE,
	IPT_END_DATE DATE,
	IPT_START_TIME VARCHAR2(4),
	IPT_END_TIME VARCHAR2(4),
    IPT_TECHNOLOGY	VARCHAR2(100),
	IPT_TRAINING_OBJECTIVES 	VARCHAR2(1000),
	IPT_LOCATION VARCHAR2(200),
	IPT_NOMINATION_FILE VARCHAR2(200),
	CONSTRAINT fk_ipt_tstatus_id
		FOREIGN KEY (TSTATUS_ID)
		REFERENCES TRAINING_STATUS(TSTATUS_ID),
	CONSTRAINT fk_ipt_tt_id
		FOREIGN KEY (TT_ID)
		REFERENCES TRAINING_TYPE(TT_ID),
	CONSTRAINT fk_ipt_ld_user_email
		FOREIGN KEY (LD_USER_EMAIL)
		REFERENCES LD_TEAM(LD_USER_EMAIL),
    CONSTRAINT fk_ipt_ver_id
        FOREIGN KEY (VER_ID)
        REFERENCES VERTICAL_TYPE(VER_ID)
);

CREATE TABLE CONFIRMED_TRAINING(
	CT_ID INT PRIMARY KEY,
	TSTATUS_ID INT,
	TT_ID INT,
	LD_USER_EMAIL VARCHAR2(50),
    VER_ID INT,
	TRF_IDS VARCHAR2(30),
	CT_START_DATE DATE,
	CT_END_DATE DATE,
	CT_START_TIME VARCHAR2(4),
	CT_END_TIME VARCHAR2(4),
    CT_TECHNOLOGY	VARCHAR2(100),
	CT_TRAINING_OBJECTIVES 	VARCHAR2(1000),
	CT_LOCATION VARCHAR2(200),
	CT_NOMINATION_FILE VARCHAR2(200),
	CONSTRAINT fk_ct_tstatus_id
		FOREIGN KEY (TSTATUS_ID)
		REFERENCES TRAINING_STATUS(TSTATUS_ID),
	CONSTRAINT fk_ct_tt_id
		FOREIGN KEY (TT_ID)
		REFERENCES TRAINING_TYPE(TT_ID),
	CONSTRAINT fk_ct_ld_user_email
		FOREIGN KEY (LD_USER_EMAIL)
		REFERENCES LD_TEAM(LD_USER_EMAIL),
    CONSTRAINT fk_ct_ver_id
        FOREIGN KEY (VER_ID)
        REFERENCES VERTICAL_TYPE(VER_ID)
);

CREATE TABLE INTERNAL_TRAINING(
	IT_ID INT PRIMARY KEY,
	CT_ID INT,
	LDTM_ID INT,
	CONSTRAINT fk_it_ct_id
		FOREIGN KEY (CT_ID)
		REFERENCES CONFIRMED_TRAINING(CT_ID),
	CONSTRAINT fk_it_ldtm_id
		FOREIGN KEY (LDTM_ID)
		REFERENCES LD_TRAINING_MEMBER(LDTM_ID)
);

CREATE TABLE DEV_TRAINING(
	DT_ID INT PRIMARY KEY,
	CT_ID INT,
	DTM_ID INT,
	CONSTRAINT fk_dt_ct_id
		FOREIGN KEY (CT_ID)
		REFERENCES CONFIRMED_TRAINING(CT_ID),
	CONSTRAINT fk_dt_dtm_id
		FOREIGN KEY (DTM_ID)
		REFERENCES DEVELOPER_TRAINING_MEMBER(DTM_ID)
);

CREATE TABLE VENDOR_TRAINING(
	VT_ID INT PRIMARY KEY,
	CT_ID INT,
	VEN_ID INT,
	CONSTRAINT fk_vt_ct_id
		FOREIGN KEY (CT_ID)
		REFERENCES CONFIRMED_TRAINING(CT_ID),
	CONSTRAINT fk_vt_ven_id
		FOREIGN KEY (VEN_ID)
		REFERENCES VENDOR(VEN_ID)
);












